version: '3.9'

services:
  discord-bot:
    build: 
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
